package com.touba.backend.exception;

public final class ErrorCode {

    public static final String AUTH_BAD_CREDENTIALS = "AUTH_BAD_CREDENTIALS";
    public static final String ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND";
    public static final String VALIDATION_INVALID_ENTITY = "VALIDATION_INVALID_ENTITY";

    public static final String VALIDATION_ACCUEILLANT_INVALID = "VALIDATION_ACCUEILLANT_INVALID";
    public static final String VALIDATION_CHAMBRE_INVALID = "VALIDATION_CHAMBRE_INVALID";
    public static final String VALIDATION_DELEGATION_INVALID = "VALIDATION_DELEGATION_INVALID";
    public static final String VALIDATION_EVENEMENT_INVALID = "VALIDATION_EVENEMENT_INVALID";
    public static final String VALIDATION_INVITE_INVALID = "VALIDATION_INVITE_INVALID";
    public static final String VALIDATION_PAVILLON_INVALID = "VALIDATION_PAVILLON_INVALID";
    public static final String VALIDATION_RESERVATION_INVALID = "VALIDATION_RESERVATION_INVALID";
    public static final String VALIDATION_RESIDENCE_INVALID = "VALIDATION_RESIDENCE_INVALID";
    public static final String VALIDATION_RESPONSABLE_INVALID = "VALIDATION_RESPONSABLE_INVALID";
    public static final String VALIDATION_UTILISATEUR_INVALID = "VALIDATION_UTILISATEUR_INVALID";

    public static final String ACCUEILLANT_ID_REQUIRED = "ACCUEILLANT_ID_REQUIRED";
    public static final String ACCUEILLANT_NOT_FOUND = "ACCUEILLANT_NOT_FOUND";
    public static final String ACCUEILLANT_RESIDENCE_REQUIRED = "ACCUEILLANT_RESIDENCE_REQUIRED";
    public static final String CHAMBRE_CAPACITY_POSITIVE = "CHAMBRE_CAPACITY_POSITIVE";
    public static final String CHAMBRE_CAPACITY_REQUIRED = "CHAMBRE_CAPACITY_REQUIRED";
    public static final String CHAMBRE_ID_REQUIRED = "CHAMBRE_ID_REQUIRED";
    public static final String CHAMBRE_NOT_FOUND = "CHAMBRE_NOT_FOUND";
    public static final String CHAMBRE_NUMBER_REQUIRED = "CHAMBRE_NUMBER_REQUIRED";
    public static final String CHAMBRE_PAVILLON_ID_REQUIRED = "CHAMBRE_PAVILLON_ID_REQUIRED";
    public static final String CHAMBRE_PAVILLON_REQUIRED = "CHAMBRE_PAVILLON_REQUIRED";
    public static final String DELEGATION_LEADER_REQUIRED = "DELEGATION_LEADER_REQUIRED";
    public static final String DELEGATION_NAME_REQUIRED = "DELEGATION_NAME_REQUIRED";
    public static final String DELEGATION_NOT_FOUND = "DELEGATION_NOT_FOUND";
    public static final String DELEGATION_SIZE_REQUIRED = "DELEGATION_SIZE_REQUIRED";
    public static final String EVENEMENT_NAME_REQUIRED = "EVENEMENT_NAME_REQUIRED";
    public static final String EVENEMENT_NOT_FOUND = "EVENEMENT_NOT_FOUND";
    public static final String INVITE_DELEGATION_REQUIRED = "INVITE_DELEGATION_REQUIRED";
    public static final String INVITE_FIRST_NAME_REQUIRED = "INVITE_FIRST_NAME_REQUIRED";
    public static final String INVITE_LAST_NAME_REQUIRED = "INVITE_LAST_NAME_REQUIRED";
    public static final String INVITE_NOT_FOUND = "INVITE_NOT_FOUND";
    public static final String INVITE_PHONE_REQUIRED = "INVITE_PHONE_REQUIRED";
    public static final String PAVILLON_LABEL_REQUIRED = "PAVILLON_LABEL_REQUIRED";
    public static final String PAVILLON_NOT_FOUND = "PAVILLON_NOT_FOUND";
    public static final String PAVILLON_RESIDENCE_REQUIRED = "PAVILLON_RESIDENCE_REQUIRED";
    public static final String RESERVATION_ARRIVAL_DATE_REQUIRED = "RESERVATION_ARRIVAL_DATE_REQUIRED";
    public static final String RESERVATION_DEPARTURE_DATE_REQUIRED = "RESERVATION_DEPARTURE_DATE_REQUIRED";
    public static final String RESERVATION_EVENT_REQUIRED = "RESERVATION_EVENT_REQUIRED";
    public static final String RESERVATION_GUEST_FIRST_NAME_REQUIRED = "RESERVATION_GUEST_FIRST_NAME_REQUIRED";
    public static final String RESERVATION_GUEST_LAST_NAME_REQUIRED = "RESERVATION_GUEST_LAST_NAME_REQUIRED";
    public static final String RESERVATION_GUEST_PHONE_REQUIRED = "RESERVATION_GUEST_PHONE_REQUIRED";
    public static final String RESERVATION_GUEST_ROOM_REQUIRED = "RESERVATION_GUEST_ROOM_REQUIRED";
    public static final String RESERVATION_GUESTS_REQUIRED = "RESERVATION_GUESTS_REQUIRED";
    public static final String RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND";
    public static final String RESERVATION_PERIOD_REQUIRED = "RESERVATION_PERIOD_REQUIRED";
    public static final String RESIDENCE_ADDRESS_REQUIRED = "RESIDENCE_ADDRESS_REQUIRED";
    public static final String RESIDENCE_LABEL_REQUIRED = "RESIDENCE_LABEL_REQUIRED";
    public static final String RESIDENCE_MANAGER_FIRST_NAME_REQUIRED = "RESIDENCE_MANAGER_FIRST_NAME_REQUIRED";
    public static final String RESIDENCE_MANAGER_LAST_NAME_REQUIRED = "RESIDENCE_MANAGER_LAST_NAME_REQUIRED";
    public static final String RESIDENCE_MANAGER_PHONE_REQUIRED = "RESIDENCE_MANAGER_PHONE_REQUIRED";
    public static final String RESIDENCE_MANAGER_REQUIRED = "RESIDENCE_MANAGER_REQUIRED";
    public static final String RESIDENCE_NOT_FOUND = "RESIDENCE_NOT_FOUND";
    public static final String RESIDENCE_PHONE_REQUIRED = "RESIDENCE_PHONE_REQUIRED";
    public static final String RESPONSABLE_FIRST_NAME_REQUIRED = "RESPONSABLE_FIRST_NAME_REQUIRED";
    public static final String RESPONSABLE_LAST_NAME_REQUIRED = "RESPONSABLE_LAST_NAME_REQUIRED";
    public static final String RESPONSABLE_NOT_FOUND = "RESPONSABLE_NOT_FOUND";
    public static final String RESPONSABLE_PHONE_REQUIRED = "RESPONSABLE_PHONE_REQUIRED";
    public static final String RESPONSABLE_RESIDENCE_REQUIRED = "RESPONSABLE_RESIDENCE_REQUIRED";
    public static final String ROLE_ADMIN_NOT_FOUND = "ROLE_ADMIN_NOT_FOUND";
    public static final String ROLE_RESPONSABLE_NOT_FOUND = "ROLE_RESPONSABLE_NOT_FOUND";
    public static final String USER_FIRST_NAME_REQUIRED = "USER_FIRST_NAME_REQUIRED";
    public static final String USER_ID_REQUIRED = "USER_ID_REQUIRED";
    public static final String USER_LAST_NAME_REQUIRED = "USER_LAST_NAME_REQUIRED";
    public static final String USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED";
    public static final String USER_NOT_FOUND = "USER_NOT_FOUND";
    public static final String USER_PHONE_REQUIRED = "USER_PHONE_REQUIRED";

    private ErrorCode() {
    }
}
